### ISSUE TITLE
Helpers for R version

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgman#21]
They’re not a perfect match for this package, but the base functions are painfully inconsistent and clearly rightly related to package installs.

**Comment by jimhester** [comment]
They could also go in rlang potentially, as checking the R version is also useful for things unrelated to package installation like function backports.

**Comment by hadley** [comment]
I'm thinking more of a user facing tool matching the api that you use to get version (and other info?) about a package (or a library?).

**Comment by jimhester** [comment]
Ah sure that makes sense

**Comment by jimhester** [comment]
Actually it doesn't make sense, @hadley could you clarify what specifically you were talking about with this issue?

**Comment by hadley** [comment]
I can't remember. I'll file again with more description if it comes up again.
