### ISSUE TITLE
Support for project package libraries

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgman#31]
Project library mode can be turned on via an option. (`options`?)

`ROOT` is the root directory of the current project. In general `ROOT/r-pkgs` is used as the default package library. The dependencies in `ROOT/DESCRIPTION` is used as the list of packages to install/update/etc.

`pkg_install`:
- [x] if called without arguments, it uses the local `DESCRIPTION` file to get the set of desired packages.
- [ ] if called with one or more packages, it installs them to the local library, and (by default) also adds them to the local `DESCRIPTION` file.
- [ ] it should be able to remove superfluous packages from the package library.
- [x] it errors if `DESCRIPTION` is not present.
- [x] it creates `r-pkgs` if it does not exist.

`pkg_status`:
- [x] show project library data by default

`pkg_remove`:
- [ ] removes package from the project library, and also from `DESCRIPOTION` (by default)

`devtools` support:
- [ ] `devtools` sets the library path to the project package library, at `load_all()` or for any function that manipulates the package, e.g. `check`, `test`, etc.
- [ ] it errors out if the project package library does not exist, or incomplete, telling you to call `pkg_install`
- [ ] it checks that the installed versions satisfy the required ones. This might need to go online, though, e.g. to check if a GH version is the latest. So we might need a lighter version of the satisfies function.
- [ ] it removes other project package libraries from the library path.

**Comment by gaborcsardi** [comment]
Maybe we want this in another package, actually.

**Comment by gaborcsardi** [comment]
OK, so for now, it is actually easy to do just a `lib_activate()` call to put the local library in the library path. (Maybe after a `dir.create` to create it.)

**Comment by pgensler** [comment]
@gaborcsardi so is this functionality meant to be able to run something like `ls -l /usr/lib/` to see that a system library is missing for a package like say `reprex` or `rJava` ?  It would probably need to be in a separate package, but is unquestionably very usefull.

**Comment by liutiming** [comment]
thanks for this awesome package! is there an update on this? working on a cluster and hence no enough storage in the home directory...
