### ISSUE TITLE
Missing status update

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgman#36]
```
> pkgman::pkg_install("tidyverse/haven")
  Updating CRAN metadata                                                                                                      
✔ CRAN metadata current                                                                                                       
✔ Found 26 dependencies for 1 packages in 939ms                                                                               
  Downloading packages [1/1] [393.01 kB] 00:00:01                                                                             
```

Then nothing happened for a while, presumably because haven is building from source, but we need something to say that's happening

**Comment by gaborcsardi** [comment]
The package build happens in the foreground currently, so we cannot update the status. https://github.com/r-lib/pkgdepends/issues/57 will fix it, eventually, but it needs a bunch of infrastructure.

**Comment by hadley** [comment]
I just meant we need a bullet like: "• Starting to build package"

**Comment by gaborcsardi** [comment]
Yeah, good point, it should do that. I haven't built anything with vignettes, so did not notice this.

Moved over here: https://github.com/r-lib/pkgdepends/issues/81
