### ISSUE TITLE
Source installs sometimes prompt about vignettes

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgman#37]
```
> pkgman::pkg_install("cran/haven")
  Updating CRAN metadata                                                                                                      
✔ CRAN metadata current                                                                                                       
✔ Found 26 dependencies for 1 packages in 864ms                                                                               
  Downloading packages [1/1] [236.53 kB] 00:00:00Building the package will delete...                                          
  '/private/tmp/RtmpyGVI7h/file616a53bf3a99/cran-haven-3d4f402/inst/doc'
Are you sure?

1: Yes
2: No
```

Two problems:

* Shouldn't need to build from source
* When building from source, shouldn't try to rebuild vignettes

**Comment by gaborcsardi** [comment]
The CRAN package is `cran::haven`, that does not build from source, at least on macOS. 

I don't know if `pkginstall` -> `pkgbuild` will rebuild the vignettes, maybe @jimhester does.

**Comment by jimhester** [comment]
`pkginstall` just calls `pkgbuild::build()` the default arg of `vignettes = TRUE`, so it does try to re-build the vignettes (and this is why you get the deletion prompt). In this case we would want to turn this off, but it is slightly tricky to do so as you would only want to turn off building vignettes in those packages which already have built vignettes.

**Comment by gaborcsardi** [comment]
A proper source package should already have the vignettes, right? Then `pkginstall` only needs to call `pkgbuild::build()` to create the binary package, i.e. to do `R CMD INSTALL`.

I guess that means `vignettes = FALSE`, no?

**Comment by hadley** [comment]
A source package from CRAN will have them, but a source package from github won't. Right?

**Comment by gaborcsardi** [comment]
`pkgdepends` will call `pkgbuild::build` on the GH tree, that builds a source package with vignettes included, right?

**Comment by gaborcsardi** [comment]
But @jimhester has a point in the other repo: https://github.com/r-lib/pkgdepends/issues/81#issuecomment-358111241

This will compile the package twice, which does not make sense to `pkgman`.

**Comment by jimhester** [comment]
Yeah, however as I mentioned in the other issue, we may not want to do that though as it requires the package to be compiled twice.

**Comment by gaborcsardi** [comment]
For `repoman` it kind of makes sense, because you want to create a proper _source_ package, with vignettes, and put it in the repo. Then it will be compiled again on the user's machine, when they install it.

But for `pkgman` we should avoid the compilation. This should be easy, because the `download` method is different to `repoman` and `pkgman`.

So, what if `pkgdepends` does `pkgbuild::build(binary = TRUE, vignettes = TRUE)` instead? Then `pkginstall` will get a binary package.

**Comment by gaborcsardi** [comment]
This way `pkginstall` always get a proper source or binary package, with vignettes, AFAICT.

**Comment by gaborcsardi** [comment]
The only glitch is that currently, `pkginstall` can build in parallel, `pkgdepends` can not. 

So another solution is that we just include it in the install plan, whether you need `vignettes = TRUE`, and `pkgdepends` will just use `vignettes = FALSE` when working for `pkgman`.

**Comment by jimhester** [comment]
I think putting it in the install plan makes the most sense, since we already have the error parsing code / parallel building in pkginstall

**Comment by gaborcsardi** [comment]
OK, sounds good, let's do this.

OTOH, that code would be handy in `pkgdepends` as well, when working for the `repoman`. 

(The error parsing code, not the parallel code, `pkgdepends` needs different parallel code, unfortunately.)

Should the error parsing code live in `pkgbuild`? That is supposed to build the binary package after all.

**Comment by gaborcsardi** [comment]
Here is the other end: https://github.com/r-lib/pkginstall/issues/24

I think we can close this issue now?

**Comment by jimhester** [comment]
Yeah, probably it should be in pkgbuild
