### ISSUE TITLE
Thoughts on initial bullets

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgman#40]
Currently we get:

```
> pkg_install("tidyverse/rlang")
  Updating CRAN metadata                                                                                     
✔ CRAN metadata current                                                                                      
✔ Found 1 dependencies for 1 packages in 4.1s                                                                
✔                                                                                                            
✔ Built rlang (6.3s)                                                                                         
✔ Installed rlang (51ms)                                                                                     
Installed rlang_0.1.6.9003_594974198a0918a2983409bf79068a671ec089ab.tar.gz (7.3s).                           
```

* [x] I think `Updating CRAN metadata` should get a tick in front of it
* [x] Should we start with something like "Installing 1 package" ?
* [x] There's an empty check mark after "found dependencies"
* [x] Why is "found 1 dependencies" in red?
* [x] Can we a have final bullet more like "Installed rlang 0.1.6 (sha1) from GitHub" ?

**Comment by gaborcsardi** [comment]
> I think Updating CRAN metadata should get a tick in front of it

Good idea, but not really possible, because it runs asynchronously, concurrently with other stuff, e.g. BioC updates, or GH queries. We can maybe use another character, to denote that this a start of something.

> There's an empty check mark after "found dependencies"

Must be a bug involving the `pkgman` progress bar. It does not happen to me, though.

> Why is "found 1 dependencies" in red?

I think because it is a `message`, and RStudio colors all messages red? Anyway, we can fix this, it is part of the "consolidating output" issue. We should not use `message`.

**Comment by jimhester** [comment]
Maybe we should just remove the `Updating CRAN metadata` line entirely then? Not completely ideal because you don't get immediate feedback about what is happening...

**Comment by gaborcsardi** [comment]
Yeah, I actually added it, because otherwise nothing might happen for 1-4 secs. My plan is to add a download progress bar there, actually. More precisely, to integrate it to the resolution progress bar.

**Comment by hadley** [comment]
I don't get the empty check mark every time 😬 

I think just using a bullet in front of "updating cran" would be fine

**Comment by gaborcsardi** [comment]
> I don't get the empty check mark every time 😬

I am not entirely sure, but it seems that both the parent and the child processes are printing to the screen, so there is racing.

**Comment by gaborcsardi** [comment]
I think these are all done. Except for the  "Updating CRAN metadata" that came up in the comments, but I'll address that as well, soon.
