### ISSUE TITLE
Can't toggle between cran & github versions

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgman#5]
``` r
pkgman::pkg_install("tidyverse/tidyverse")
#> ✔ Resolving dependencies
pkgman::pkg_install("tidyverse")
#> ✔ Resolving dependencies
```

**Comment by jimhester** [comment]
pkg_reinstall to reinstall a installed package.

**Comment by gaborcsardi** [comment]
But should reinstall always use the same refs? Or only if no refs are
supplied?

**Comment by hadley** [comment]
`pkg_reinstall(x)` would behave like `pkg_install(x)` except that it would force the installation of all packages listed in `x` (i.e. it would not be checked if they were already installed). It doesn't use information about the current install.

**Comment by gaborcsardi** [comment]
That's more like pkg_install(force=TRUE, ...), no?

**Comment by hadley** [comment]
Right - I think it's sufficiently different that it deserves it's own function (and you could imagine it having `recursive = TRUE`)

**Comment by jimhester** [comment]
This should now be fixed by upstream changes in pkgdepends.

**Comment by gaborcsardi** [comment]
Yes, although there are still some `pkgdepends` changes required.

**Comment by gaborcsardi** [comment]
OK, should be good now:
```r
❯ pkg_install("r-lib/crayon")
✔ Resolving dependencies
✔ Built crayon (832ms)
✔ Installed crayon (42ms)
Installed crayon_1.3.4_b5221ab0246050dc687dc8b9964d5c44c947b265.tar.gz (1.6s).

❯ pkg_install("r-lib/crayon")
✔ Resolving dependencies
✔ r-lib/crayon and its 1 dependencies already installed

❯ pkg_install("cran::crayon")
✔ Resolving dependencies
✔ Installed crayon (89ms)
Installed crayon_1.3.4.tgz (738ms).

❯ pkg_install("cran::crayon")
✔ Resolving dependencies
✔ cran::crayon and its 1 dependencies already installed

❯ pkg_install("r-lib/crayon")
✔ Resolving dependencies
✔ Built crayon (834ms)
✔ Installed crayon (37ms)
Installed crayon_1.3.4_b5221ab0246050dc687dc8b9964d5c44c947b265.tar.gz (1.5s).
```

**Comment by hadley** [comment]
Nice!
