### ISSUE TITLE
More info about what's going to happen

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgman#7]
In between resolving dependencies and download, it would be nice to get a message about how many packages need to be installed

**Comment by jimhester** [comment]
Agreed I think most of the plumbing for more useful progress bars is in pkgdepends, but the progress bar could be fleshed out some (https://github.com/r-lib/pkgdepends/issues/7)

**Comment by gaborcsardi** [comment]
Yeah, and that is going to happen, soon.

**Comment by hadley** [comment]
This is now much better
