### ISSUE TITLE
Some confusion on the byte sizes of downloaded / cached packages

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkgman#73]
I was a little confused by the output for this

```
> pkgman::pkg_install("github::tidyverse/dplyr")
ℹ Loading global cached package metadata
ℹ Loading global cached package metadata
✔ Using cached package metadata

→ Will update 1 packages:
  github::tidyverse/dplyr

→ Will not update 17 packages.

→ Will download 0 packages (0 B), cached: 1 (0 B).

? Do you want to continue (Y/n)
ℹ Building dplyr 0.7.99.9000
✔ Built dplyr 0.7.99.9000 [29.1s]
✔ Installed dplyr 0.7.99.9000 (github::tidyverse/dplyr@7105bbd) [109ms]
✔ 1 + 17 pkgs | kept 17, updated 1, new 0 | downloaded 1 (0 B) [43.9s]
```

In particular

> → Will download 0 packages (0 B), cached: 1 (0 B).

I thought we would have to download at least the GH package, but then I decided maybe not since it was in the cache already. But if that was the case I would expect the size for the cached packages to be more than `0 B`.

Also not sure why we are getting the following message twice, particularly when we later have the 'Using cached package metadata' message.

> ℹ Loading global cached package metadata

**Comment by gaborcsardi** [comment]
Yeah, will fix. The download sizes are sometimes not known, e.g. for GH, will change  the message(s) in this case....

**Comment by gaborcsardi** [comment]
I think these are OK now. Atleast much better.
